# Site settings
title: Emrass Blog
email: enrico.mrass@gmail.com
description: >
  Hi, I'm Enrico. I blog about web development, software architecture and entrepreneurship with occasional musings about music, food or life in general
baseurl: ""
url: "http://emrass.de"
twitter_username: _emrass
github_username:  emrass
bitbucket_username: emrass
email_username: "enrico.mrass@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge

# Grunt handles images and assets
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']
